// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenH3K8XK4aa3zL-IyVj6AZd9CnZsQlHU',
    appId: '1:385201508196:web:fb0729c2e2aaef2530b471',
    messagingSenderId: '385201508196',
    projectId: 'foodapp-72c2a',
    authDomain: 'foodapp-72c2a.firebaseapp.com',
    storageBucket: 'foodapp-72c2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrjq4qnFH8FXiSz8lsYVfmdBirYlsTiw',
    appId: '1:385201508196:android:b8944fee8c88384330b471',
    messagingSenderId: '385201508196',
    projectId: 'foodapp-72c2a',
    storageBucket: 'foodapp-72c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrm3KGfh3Xc3nbWCddo01BD3pE2nWhJ0',
    appId: '1:385201508196:ios:96148566b4a4c46830b471',
    messagingSenderId: '385201508196',
    projectId: 'foodapp-72c2a',
    storageBucket: 'foodapp-72c2a.appspot.com',
    iosClientId: '385201508196-q009uc1f2g6tgdb1c3sbnhmsan02qpae.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVrm3KGfh3Xc3nbWCddo01BD3pE2nWhJ0',
    appId: '1:385201508196:ios:ce7d81352b90a40d30b471',
    messagingSenderId: '385201508196',
    projectId: 'foodapp-72c2a',
    storageBucket: 'foodapp-72c2a.appspot.com',
    iosClientId: '385201508196-i46b02v4a4j9bhjqipvii584sua72fqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
